export const INVESTOR_CHARTER_DATA = {
  title: "INVESTOR CHARTER IN RESPECT OF RAS",
  sections: [
    {
      id: "A",
      title: "Vision and Mission Statements for investors",
      content: [
        { type: "paragraph", text: "Vision" },
        { type: "list", items: ["Invest with knowledge & safety."] },
        { type: "paragraph", text: "Mission" },
        { type: "list", items: ["Every investor should be able to invest in right investment products based on their needs, manage and monitor them to meet their goals, access reports and enjoy financial wellness."] },
      ],
    },
    {
      id: "B",
      title: "Details of business transacted by the Research Analyst with respect to the investors",
      content: [
        { type: "list", items: [
          "To publish research report based on the research activities of the RA",
          "To provide an independent unbiased view on securities.",
          "To offer unbiased recommendation, disclosing the financial interests in recommended securities.",
          "To provide research recommendation, based on analysis of publicly available information and known observations.",
          "To conduct audit annually",
          "To ensure that all advertisements are in adherence to the provisions of the Advertisement Code for Research Analysts.",
          "To maintain records of interactions, with all clients including prospective clients (prior to onboarding), where any conversation related to the research services has taken place.",
        ]},
      ],
    },
    {
      id: "C",
      title: "Details of services provided to investors (No Indicative Timelines)",
      content: [
        { type: "heading", level: 3, text: "Onboarding of Clients" },
        { type: "list", items: [
          "Sharing of terms and conditions of research services",
          "Completing KYC of fee paying clients",
        ]},
        { type: "heading", level: 3, text: "Disclosure to Clients:" },
        { type: "list", items: [
          "To disclose, information that is material for the client to make an informed decision, including details of its business activity, disciplinary history, the terms and conditions of research services, details of associates, risks and conflicts of interest, if any",
          "To disclose the extent of use of Artificial Intelligence tools in providing research services",
          "To disclose, while distributing a third party research report, any material conflict of interest of such third party research provider or provide web address that directs a recipient to the relevant disclosures",
          "To disclose any conflict of interest of the activities of providing research services with other activities of the research analyst.",
          "To distribute research reports and recommendations to the clients without discrimination.",
          "To maintain confidentiality w.r.t publication of the research report until made available in the public domain.",
          "To respect data privacy rights of clients and take measures to protect unauthorized use of their confidential information",
          "To disclose the timelines for the services provided by the research analyst to clients and ensure adherence to the said timelines",
          "To provide clear guidance and adequate caution notice to clients when providing recommendations for dealing in complex and high-risk financial products/services",
          "To treat all clients with honesty and integrity",
          "To ensure confidentiality of information shared by clients unless such information is required to be provided in furtherance of discharging legal obligations or a client has provided specific consent to share such information.",
        ]},
      ],
    },
    {
      id: "D",
      title: "Details of grievance redressal mechanism and how to access it",
      content: [
        { type: "paragraph", text: "1. Investor can lodge complaint/grievance against Research Analyst in the following ways:" },
        { type: "heading", level: 4, text: "Mode of filing the complaint with research analyst" },
        { type: "paragraph", text: "In case of any grievance / complaint, an investor may approach the concerned Research Analyst who shall strive to redress the grievance immediately, but not later than 21 days of the receipt of the grievance." },
        { type: "heading", level: 4, text: "Mode of filing the complaint on SCORES or with Research Analyst Administration and Supervisory Body (RAASB)" },
        { type: "list", items: [
          "SCORES 2.0 (a web based centralized grievance redressal system of SEBI for facilitating effective grievance redressal in time-bound manner) (https://scores.sebi.gov.in)",
          "Two level review for complaint/grievance against Research Analyst:",
          "First review done by designated body (RAASB)",
          "Second review done by SEBI",
          "Email to designated email ID of RAASB",
        ]},
        { type: "paragraph", text: "2. If the Investor is not satisfied with the resolution provided by the Market Participants, then the Investor has the option to file the complaint/ grievance on SMARTODR platform for its resolution through online conciliation or arbitration." },
        { type: "paragraph", text: "With regard to physical complaints, investors may send their complaints to:" },
        { type: "address", items: [
          "Office of Investor Assistance and Education,",
          "Securities and Exchange Board of India,",
          "SEBI Bhavan, Plot No. C4-A, 'G' Block,",
          "Bandra-Kurla Complex, Bandra (E),",
          "Mumbai-400 051",
        ]},
      ],
    },
    {
      id: "E",
      title: "Rights of investors",
      content: [
        { type: "list", items: [
          "Right to Privacy and Confidentiality",
          "Right to Transparent Practices",
          "Right to fair and Equitable Treatment",
          "Right to Adequate Information",
          "Right to Initial and Continuing Disclosure",
          "Right to receive information about all the statutory and regulatory disclosures",
          "Right to Fair & True Advertisement",
          "Right to Awareness about Service Parameters and Turnaround Times",
          "Right to be informed of the timelines for each service",
          "Right to be Heard and Satisfactory Grievance Redressal",
          "Right to have timely redressal",
          "Right to Exit from Financial product or service in accordance with the terms and conditions agreed with the research analyst",
          "Right to receive clear guidance and caution notice when dealing in Complex and High-Risk Financial Products and Services",
        ]},
        { type: "heading", level: 4, text: "Additional Rights to vulnerable consumers" },
        { type: "list", items: [
          "Right to get access to services in a suitable manner even if differently abled",
          "Right to provide feedback on the financial products and services used",
          "Right against coercive, unfair, and one-sided clauses in financial agreements",
        ]},
      ],
    },
    {
      id: "F",
      title: "Expectations from the investors (Responsibilities of investors)",
      content: [
        { type: "heading", level: 4, text: "Do's" },
        { type: "list", items: [
          "Always deal with SEBI registered Research Analyst.",
          "Ensure that the Research Analyst has a valid registration certificate.",
          "Check for SEBI registration number. Please refer to the list of all SEBI registered Research Analyst which is available on SEBI website in the following link: https://www.sebi.gov.in/sebiweb/other/OtherAction.do?doRecognisedFpi=yes&intmId=14)",
          "Always pay attention towards disclosures made in the research reports before investing.",
          "Pay your Research Analyst through banking channels only and maintain duly signed receipts mentioning the details of your payments. You may make payment of fees through Centralized Fee Collection Mechanism (CeFCoM) of RAASB if research analyst has opted for the mechanism. (Applicable for fee paying clients only)",
          "Before buying/ selling securities or applying in public offer, check for the research recommendation provided by your Research Analyst.",
          "Ask all relevant questions and clear your doubts with your Research Analyst before acting on recommendation.",
          "Seek clarifications and guidance on research recommendations from your Research Analyst, especially if it involves complex and high risk financial products and services.",
          "Always be aware that you have the right to stop availing the service of a Research Analyst as per the terms of service agreed between you and your Research Analyst.",
          "Always be aware that you have the right to provide feedback to your Research Analyst in respect of the services received.",
          "Always be aware that you will not be bound by any clause, prescribed by the research analyst, which is contravening any regulatory provisions.",
          "Inform SEBI about Research Analyst offering assured or guaranteed returns.",
        ]},
        { type: "heading", level: 4, text: "Don'ts" },
        { type: "list", items: [
          "Do not provide funds for investment to the Research Analyst.",
          "Don't fall prey to luring advertisements or market rumors.",
          "Do not get attracted to limited period discount or other incentive, gifts, etc. offered by Research Analyst.",
          "Do not share login credential and password of your trading, demat or bank accounts with the Research Analyst.",
        ]},
      ],
    },
  ],
} as const;